---
LOGGING:
  level: "INFO"
  format: "%(asctime)s %(levelname)-8s %(message)s"
  filemode: "w"
  file: "default_logfile.log"
  dateformat: "%Y-%m-%d %H:%M:%S"
HYPERPARAMETERS_UUV8:
  capacity: "16"
  init_energy: "16"
  init_observation: "143"
  init_belief_support: "[143]"
  horizon: "100"
  iterations: "800"
  precomputed_shield: "False"
  precomputed_cpomdp: "True"
  pickled_action_shield_file: "as_8"
  pickled_cpomdp: "cpomdp_8"
  sparse: "True"

HYPERPARAMETERS_UUV12:
  capacity: "16"
  init_energy: "16"
  init_observation: "143"
  init_belief_support: "[143]"
  horizon: "100"
  precomputed_shield: "False"
  precomputed_cpomdp: "True"
  pickled_action_shield_file: "as_12"
  pickled_cpomdp: "cpomdp_12"
  iterations: "1000"
  sparse: "True"

HYPERPARAMETERS_UUV16:
  capacity: "16"
  init_energy: "16"
  init_observation: "143"
  init_belief_support: "[143]"
  horizon: "100"
  precomputed_shield: "False"
  precomputed_cpomdp: "True"
  pickled_action_shield_file: "as_16"
  pickled_cpomdp: "cpomdp_16"
  iterations: "1000"
  sparse: "True"

HYPERPARAMETERS_UUV20:
  capacity: "16"
  init_energy: "16"
  init_observation: "143"
  init_belief_support: "[143]"
  horizon: "100"
  precomputed_shield: "False"
  precomputed_cpomdp: "True"
  pickled_action_shield_file: "as_20"
  pickled_cpomdp: "cpomdp_20"
  iterations: "1000"
  sparse: "True"

HYPERPARAMETERS_NYC:
  capacity: "600"
  init_energy: "600"
  init_observation: "1"
  horizon: "1000"
  precomputed_shield: "False"
  precomputed_cpomdp: "True"
  pickled_action_shield_file: "as_nyc"
  pickled_cpomdp: "cpomdp_nyc"
  iterations: "100"

HYPERPARAMETERS_TIGER:
  capacity: "10"
  init_energy: "10"
  init_observation: "0"
  init_belief_support: "tuple([0, 1])"
  horizon: "500"
  precomputed_shield: "False"
  precomputed_cpomdp: "True"
  pickled_action_shield_file: "as_tiger"
  pickled_cpomdp: "cpomdp_tiger"
  iterations: "100"
  listen_uncertainty: 0.15
  swap_probability: 0.2

HYPERPARAMETERS_GLOBAL:
  exploration: "1"
  softmax: "False"
  random_seed: "42"
  shield_on: "True"
  is_sparse: "False"
